### ISSUE TITLE
compatibility issue when upgrade to 2.3.0

### ISSUE THREAD

**Issue by ReparoZ** [tersesystems/echopraxia#238]
There was a problem when upgrading to version 2.3.0. Initially, version 2.2.4 was used and the system was working fine. However, after upgrading to version 2.3.0, the system could not start and an error message appeared stating "java.lang.ClassNotFoundException: org.slf4j.impl.StaticLoggerBinder". Upon investigation, it was discovered that version 1.4.6 of logback was being used in the system, and this version does not have the class "org.slf4j.impl.StaticLoggerBinder". Is this a compatibility issue introduced by version 2.3.0? Can it be fixed?

**Comment by ReparoZ** [comment]
<img width="791" alt="image" src="https://user-images.githubusercontent.com/16733302/230584053-39a16bc7-c830-4d35-82fe-69a77ad40219.png">
<img width="458" alt="image" src="https://user-images.githubusercontent.com/16733302/230584221-4d0d0684-7a81-49a5-949f-da9747de0ddf.png">

**Comment by wsargent** [comment]
I'll fix it, it's an issue where echopraxia races.
